import React from 'react';
import { ProductCatalog } from 'plant-faced';
import type { Product } from 'plant-faced';

const products: Product[] = [
  {
    id: 1,
    name: "Seitan's Finest - White Boxy Tee",
    urlName: 'seitans-finest-white-crop-top',
    description: 'Minimalist print tee. 100% certified organic cotton.',
    image: 'https://images.teemill.com/77051b81e961661e017a961519b4358ccc3b71a57b9102d4.png.jpg?w=640&h=auto',
    lifestyleImage: 'https://images.teemill.com/5cpusfoyjbdecs4eu9trcannhq6fh4xug91ymxogvv0p2xix.jpeg.jpg?w=640&h=auto',
    isBundle: false,
    collectionImage: '',
    collectionImageAlt: '',
    price: 28,
    totalBundlePrice: 0,
    salePrice: 0,
    colors: ['White'],
    colorThumbnails: { White: { type: 'color', value: '#ffffff' } },
    defaultColor: null,
    defaultColour: null,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    types: ['Printed T-shirt'],
    options: [],
    gender: 'female',
    ageGroup: 'adults',
    reviews: { rating: 4.6, count: 34 },
    priceRange: [28],
    salePriceRange: [],
    category: 'Camisetas',
  },
  {
    id: 2,
    name: 'Sorry I Only Date Vegans - Black Tee',
    urlName: 'sorry-i-only-date-vegans-tee-black',
    description: "Y2K-inspired design on 100% organic cotton. Heavyweight oversized fit.",
    image: 'https://images.teemill.com/38da7eae1ef8c3f906324c9988293da9d571b4ba92bc8e39.png.jpg?w=640&h=auto',
    lifestyleImage: '',
    isBundle: false,
    collectionImage: '',
    collectionImageAlt: '',
    price: 32,
    totalBundlePrice: 0,
    salePrice: 0,
    colors: ['Black'],
    colorThumbnails: { Black: { type: 'color', value: '#000000' } },
    defaultColor: null,
    defaultColour: null,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    types: ['Printed T-shirt'],
    options: [],
    gender: 'male',
    ageGroup: 'adults',
    reviews: { rating: 4.8, count: 52 },
    priceRange: [32],
    salePriceRange: [],
    category: 'Camisetas',
  },
  {
    id: 3,
    name: 'Plant Life Oversized Hoodie - Forest',
    urlName: 'plant-life-hoodie-forest',
    description: 'Heavyweight unisex hoodie in forest green. Made from 100% organic cotton.',
    image: 'https://images.teemill.com/dedgjiqttitmnooizhonqq0stmlnfln2krournfp58rbfobm.png.jpg?w=640&h=auto',
    lifestyleImage: '',
    isBundle: false,
    collectionImage: '',
    collectionImageAlt: '',
    price: 52,
    totalBundlePrice: 0,
    salePrice: 38,
    colors: ['Forest', 'Charcoal'],
    colorThumbnails: {
      Forest: { type: 'color', value: '#2d5a27' },
      Charcoal: { type: 'color', value: '#333' },
    },
    defaultColor: null,
    defaultColour: null,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    types: ['Hoodie'],
    options: [],
    gender: 'unisex',
    ageGroup: 'adults',
    reviews: { rating: 4.9, count: 87 },
    priceRange: [38, 52],
    salePriceRange: [38],
    category: 'Buzos',
  },
  {
    id: 4,
    name: 'Vegan Muscle Tank - Sage',
    urlName: 'vegan-muscle-tank-sage',
    description: 'Breathable organic cotton muscle tank.',
    image: 'https://images.teemill.com/77051b81e961661e017a961519b4358ccc3b71a57b9102d4.png.jpg?w=640&h=auto',
    lifestyleImage: '',
    isBundle: false,
    collectionImage: '',
    collectionImageAlt: '',
    price: 24,
    totalBundlePrice: 0,
    salePrice: 0,
    colors: ['Sage'],
    colorThumbnails: { Sage: { type: 'color', value: '#8faa8b' } },
    defaultColor: null,
    defaultColour: null,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    types: ['Tank top'],
    options: [],
    gender: 'female',
    ageGroup: 'adults',
    reviews: { rating: 4.4, count: 19 },
    priceRange: [24],
    salePriceRange: [],
    category: 'Musculosas',
  },
];

export function FullCatalog() {
  return (
    <div style={{ padding: '16px', minHeight: 600 }}>
      <ProductCatalog products={products} />
    </div>
  );
}
